File :- 4 - 06-06

In [2]:
import pandas as pd
import numpy as np

In [4]:
data = {
    "Category" : ["electronics" , "eletroNICs", "clothes"]
}

df = pd.DataFrame(data)

# cob=nvert into lower case 

df["caategory_lower"] = df["Category"].str.lower()

df["Categpory_upper"] = df["Category"].str.upper()

df

      Category caategory_lower Categpory_upper
0  electronics     electronics     ELECTRONICS
1   eletroNICs      eletronics      ELETRONICS
2      clothes         clothes         CLOTHES

In [6]:
df["Category_clean"] = df["Category"].str.replace("electronics", "Electronics Items")

df

      Category caategory_lower Categpory_upper     Category_clean
0  electronics     electronics     ELECTRONICS  Electronics Items
1   eletroNICs      eletronics      ELETRONICS         eletroNICs
2      clothes         clothes         CLOTHES            clothes